#!/usr/bin/env php
<?php
/**
 * 命令行模式启动脚本
 * 运行方式例如：<your_path>/App/run demo/info
 */

// 应用命名空间（请与应用所在目录名保持一致）
const APP_NAMESPACE = 'App';

// 应用路径
const APP_PATH = __DIR__;

// 命令行模式标识
const CONSOLE_MODE = true;

// 定义应用的运行环境，会自动加载带有 -dev 后缀的配置文件
const APP_ENV = 'dev';

// 是否显示错误信息（命令行模式建议开启，默认值：false）
const SHOW_ERROR = true;

// 是否开启日志（命令行模式建议开启，默认值：false）
const LOG_ON = true;

// 系统目录分隔符
const DS = DIRECTORY_SEPARATOR;

// 日志存储路径（LOG_MODE为1时生效）
const LOG_PATH = APP_PATH . DS . 'Log' . DS . 'console-log';

// 引入 MiniFramework 就是这么简单
require dirname(__DIR__) . DS . 'MiniFramework' . DS . 'Bootstrap.php';
